# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. 
on:
  # Triggers the workflow when a stable or pre-release release is published
  release:
    types: [ published ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    if: github.repository == 'andyalm/mount-aws'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      Configuration: Release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - run: dotnet build
        env:
          GithubReleaseNotes: ${{ github.event.release.body }}
          GithubReleaseTag: ${{ github.event.release.tag_name }}

      - name: Publish Module to PowerShell Gallery
        run: pwsh publish.ps1
        env:
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
    environment:
      name: PowerShell Gallery
      url: https://www.powershellgallery.com/packages/MountGitlab